### ISSUE TITLE
Can not read a block mapping entry

### ISSUE THREAD

**Issue by mikedidthis** [sojournerc/gulp-markdown-docs#3]
Firstly, thanks for the excellent work. Sadly, I seem to have hit a snag. When trying to use a yaml header, I get the following error:

```
JS-YAML: can not read a block mapping entry; a multiline key may not be an implicit key at line 12, column 1:
```

I copied the contents from [cat1file1.md](../tree/master/test/fixtures/cat1file1.md). The error can be replicated [js-yaml](http://nodeca.github.io/js-yaml/).

**Comment by sojournerc** [comment]
It looks like this might be a result of GitHub being too smart with that markdown file. 

When you copy the contents, select "Raw". It looks like the whitespace isn't being preserved for the yaml section of that file when GitHub parses the markdown.

The header should look like this with line breaks after each value:

```
---
label: Cat1File1
id: cat1file1
categorySlug: cat1
categoryLabel: ZZCat1
categoryRank: 2
```
