### ISSUE TITLE
Fails with windows line endings

### ISSUE THREAD

**Issue by joncppl** [sojournerc/gulp-markdown-docs#5]
It expects '\n\n', and therefore the splice fails if the line endings are windows style '\r\n\r\n'

**Comment by sojournerc** [comment]
I've been thinking about how to address this.

At first I thought it would just make sense to see if `process.platform` was 'win32' and then using the line ending to split on instead, but that doesn't exactly solve the problem. 

The file could have been written on a windows machine, but parsed on a unix machine, so the above method would not work.

The alternative is to detect what platform wrote the file, but I'm not sure there's a straightforward way to do that.

Definitely open to suggestions.
