### ISSUE TITLE
<table> rendering

### ISSUE THREAD

**Issue by WheelyWonka** [sojournerc/gulp-markdown-docs#7]
Hi there, thanks for this awesome gulp-thing !

Quick question, is there a way to give gulp-markdown-docs some `<table>` in html to eat and avoid the conversion to text ?  Thanks a lot !

**Comment by sojournerc** [comment]
Thanks for the feedback! It's been a while since I've looked at this project. 

I had to look at the source, but marked (used to parse the markdown) has a sanitize option that defaults to true.

Instead if you do 

```
gulp.src('some-docs/**.md')
        .pipe(gulpMarkdown('out.html', {
          markdown: {
            sanitize: false
          }
        }))
...
```

your HTML will be unescaped.

**Comment by WheelyWonka** [comment]
Indeed ! Thank you a lot.
