### ISSUE TITLE
Set Document Title

### ISSUE THREAD

**Issue by rmspeers** [sojournerc/gulp-markdown-docs#8]
I wish to be able to change the standard title for the produced HTML page from "Gulp Markdown Docs" to a value defined in my configuration.

**Comment by rmspeers** [comment]
I'm aware that I can do this by updating the index.html, it is just a suggested feature request to be able to do so without that.

**Comment by sojournerc** [comment]
Thanks for the suggestion. Pull requests are welcome.

**Comment by rmspeers** [comment]
Sounds good -- will do if I get a chance, I ended up just doing a custom HTML for now, given you allow that nicely. I guess if I don't get time to issue a PR for it, it's probably not that important ;)
